internal enum NetMessageId
{
	NEVERCALLED = 0,                    // Added
	CLIENT_SAY_HELLO = 1,
    CLIENT_KICK = 2,                    // Added
    CLIENT_PLAYER_INFO = 3,             // Added
    CLIENT_NAME_HEAD = 4,
	CLIENT_INVENTORY = 5,
	CLIENT_INVENTORY_END = 6,
    CLIENT_WORLD_DATA = 7,              // Added
    CLIENT_REQ_STARTING_DATA = 8,
    STATUS_TEXT_SIZE = 9,               // Added
    CLIENT_TILE_SECTION = 10,           // Added
    CLIENT_TILE_FRAME_SECTION = 11,     // Added
    CLIENT_PLAYER_SPAWN = 12,           // Added
    CLIENT_PLAYER_CONTROLS = 13,        // Added
    CLIENT_PLAYER_ACTIVE = 14,          // Added
    CLIENT_REQ_RESYNC = 15,
	MSG_PLAYER_LIFE = 16,
	MSG_WORLD_CHANGED = 17,
    MSG_SET_TIME = 18,                  // Added
    MSG_TOGGLE_DOOR_STATE = 19,         // Added
    UNK_MSG_20 = 20,                    // Added
    MSG_SYNC_ITEM = 21,                 // Added
    MSG_ITEM_OWNER = 22,                // Added
    MSG_SYNC_NPC = 23,                  // Added
    MSG_UNUSED_MELEE_STRIKE = 24,       // Added
    UNK_MSG_25 = 25,                    // Added
    MSG_PLAYER_DAMAGE = 26,
	MSG_PROJECTILE_INTO = 27,
	MSG_HIT_NPC = 28,
	MSG_KILL_PROJECTILE = 29,
	MSG_PLAYER_VS_PLAYER = 30,
	MSG_REQ_CHEST_ITEM = 31,
	MSG_CHEST_ITEM = 32,
	MSG_PLAYER_CHEST_VAR = 33,
	CLIENT_REQ_KILL_TILE = 34,
	MSG_PLAYER_HEAL_EFFECT = 35,
	MSG_PLAYER_ZONE_INFO = 36,
    MSG_REQ_PASSWORD = 37,              // Added
    MSG_PASSWORD = 38,
    MSG_RELEASE_ITEM_OWNERSHIP = 39,    // Added
    MSG_PLAYER_NPC_TALK = 40,
	MSG_PLAYER_GUN_ROTATION = 41,
	MSG_PLAYER_MANA = 42,
    UNK_MSG_43 = 43,                    // Added
    UNK_MSG_44 = 44,                    // Added
    UNK_MSG_45 = 45,                    // Added
    UNK_MSG_46 = 46,                    // Added
    UNK_MSG_47 = 47,                    // Added
    MSG_LIQUID_UPDATE = 48,             // Added
    MSG_INITIAL_SPAWN = 49,             // Added
    MSG_PLAYER_BUFFS = 50
}